# Generated by Django 5.2.2 on 2025-07-07 17:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('local', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='O valor de capacidade não pode ser menor que 1.'), django.core.validators.MaxValueValidator(10000, message='O valor de capacidade não pode ser maior que 10000.')])),
                ('category', models.CharField(choices=[('tecnologia', 'Técnologia'), ('educacao', 'Educação'), ('saude', 'Saúde'), ('empreendedorismo', 'Empreendedorismo')], max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
