# Generated by Django 5.2.2 on 2025-06-13 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tittle',
            new_name='title',
        ),
    ]
