# Generated by Django 5.2.2 on 2025-06-20 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='resgistration_date',
            new_name='registration_date',
        ),
    ]
